import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";
import { Footer } from "./components/footer";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased flex flex-col justify-around min-h-screen`}
      >
        <div className="flex-grow p-6 pb-20 md:overflow-y-auto md:p-12 md:pb-20 flex flex-col">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
